#Exercício 9 – Tabuada
m = int(input('digite um numero para ver sua tabuada: '))
print('__' * 12)
print('{} x {:2} = {} '.format(m, 1, m*1))
print('{} x {:2} = {} '.format(m, 2, m*2))
print('{} x {:2} = {} '.format(m, 3, m*3))
print('{} x {:2} = {} '.format(m, 4, m*4))
print('{} x {:2} = {} '.format(m, 5, m*5))
print('{} x {:2} = {} '.format(m, 6, m*6))
print('{} x {:2} = {} '.format(m, 7, m*7))
print('{} x {:2} = {} '.format(m, 8, m*8))
print('{} x {:2} = {} '.format(m, 9, m*9))
print('{} x {:2} = {} '.format(m, 10, m*10))
print('__' * 12)
